// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBY2MEM3uqTOCx8FVkDsnNTuMgFrMUy3G4',
    appId: '1:526960305639:web:975a8f895b158e14fd0942',
    messagingSenderId: '526960305639',
    projectId: 'pingolearn-assignment-34f1d',
    authDomain: 'pingolearn-assignment-34f1d.firebaseapp.com',
    storageBucket: 'pingolearn-assignment-34f1d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA5uHMdSOoqFzneISmG7QqnkzFP7H2RrgU',
    appId: '1:526960305639:android:f10d3f18dd01cb17fd0942',
    messagingSenderId: '526960305639',
    projectId: 'pingolearn-assignment-34f1d',
    storageBucket: 'pingolearn-assignment-34f1d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANEYPUgVoP_qn7ql-ZFCwbpd0KhTqZnzk',
    appId: '1:526960305639:ios:b431e056b25e84ddfd0942',
    messagingSenderId: '526960305639',
    projectId: 'pingolearn-assignment-34f1d',
    storageBucket: 'pingolearn-assignment-34f1d.appspot.com',
    iosBundleId: 'com.example.pingolearnAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANEYPUgVoP_qn7ql-ZFCwbpd0KhTqZnzk',
    appId: '1:526960305639:ios:b431e056b25e84ddfd0942',
    messagingSenderId: '526960305639',
    projectId: 'pingolearn-assignment-34f1d',
    storageBucket: 'pingolearn-assignment-34f1d.appspot.com',
    iosBundleId: 'com.example.pingolearnAssignment',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBY2MEM3uqTOCx8FVkDsnNTuMgFrMUy3G4',
    appId: '1:526960305639:web:a81e9e9cbbfdfa0dfd0942',
    messagingSenderId: '526960305639',
    projectId: 'pingolearn-assignment-34f1d',
    authDomain: 'pingolearn-assignment-34f1d.firebaseapp.com',
    storageBucket: 'pingolearn-assignment-34f1d.appspot.com',
  );
}
